name: merged_env

channels:
  - conda-forge
  - bioconda
  - r
  - defaults

dependencies:
  - python>=3.9,<3.13
  - bcftools
  - bedtools
  - biopython
  - notebook
  - numpy
  - pandas
  - matplotlib
  - obonet
  - statsmodels
  - scanpy
  - pyarrow
  - pyfaidx
  - regex
  - ucsc-bedtobigbed
  - ucsc-liftover
  - pyliftover
  - pip
